[package]
name    = "aeon"
version = "0.0.1"
authors = ["Yorick Peterse <yorickpeterse@gmail.com>"]
build   = "build.rs"

[lib]
name    = "libaeon"
doctest = false

[[bin]]
name = "aeon"
test = false

[dependencies]
getopts = "0.2"
